# Generated by Django 6.0.5 on 2026-06-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaivarity',
            name='price',
        ),
        migrations.AddField(
            model_name='chaivarity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chai/'),
        ),
    ]
