# Generated by Django 6.0.5 on 2026-06-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_remove_chaivarity_price_chaivarity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='description',
            field=models.TextField(default='No description'),
            preserve_default=False,
        ),
    ]
