# Generated by Django 6.0.5 on 2026-06-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0004_chaicertificate_chaireview_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivarity',
            name='type',
            field=models.CharField(choices=[('ML', 'MASALA'), ('GR', 'GINGER'), ('KL', 'KIWI'), ('PL', 'PLAIN'), ('EL', 'ELACHI'), ('Lm', 'LEMON'), ('IC', 'ICE'), ('Gt', 'GREEN'), ('Sf', 'Saffron'), ('BL', 'BLACK')], max_length=2),
        ),
    ]
