# Generated by Django 6.0.5 on 2026-06-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
